[package]
name = "heartland"
version = "0.1.0"
authors = ["Shane Logsdon <shane@shanelogsdon.com>"]
build = "src/build.rs"

[dependencies]
hyper     = "0.9.10"
xml-rs    = "0.3.4"
serde     = "0.8"
serde_xml = "0.8"

[build-dependencies]
serde_codegen = "0.8"
